title: Nico Vega's Website
email: ndvega@uc.cl
description: >- # this means to ignore newlines until "baseurl:"
  Looking for cool ideas, crypto-related stuff, startups? Welcome to my personal site..
twitter_username: nikelaosvega
github_username:  nicolasvegam
locale: en_US
url: https://nicovega.xyz

# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social Sharing
twitter:
  username: nikelaosvega
facebook:
  username: niqooolas
  app_id:
  publisher:
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/nikelaosvega"
    - "https://www.linkedin.com/in/nicolasvegam"

# Analytics
analytics:
  #  provider               : false # false (default), "google", "google-universal", "custom"
  provider: "google-universal"
  google:
    tracking_id: G-V6D9V5EFSQ

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
clippings: all
ignore:
  envs: development


# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : null

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
